### ISSUE TITLE
LayeredLayout ignoring layout constraints

### ISSUE THREAD

**Issue by rwvens** [microsoft/automatic-graph-layout#226]
First of all, I absolutely love MSAGL, y'all did a great job on this library, and I can say so [with great confidence](https://www.youtube.com/watch?v=BMzAs69OPXs) having previously used GraphSharp on the exact same dataset and achieving objectively inferior results.

I'm having a bit of an issue though with the constraints. While the results are great with the procedurally generated tech trees as seen in that video up there, when I try to run the layout code on an actual tech tree from my game, I run into some issues.

Here's what the layout looks like without constraints:
![Unity_tvgq6BKfY8](https://user-images.githubusercontent.com/2258788/79271966-9d746080-7e98-11ea-86c1-71bcf8cf84cf.png)

Which looks great, with one exception. Some techs that are meant to be in a linear chain get moved rather far away from their parents, such as the one labeled d0, which in my database is "Destroyer IV" (you can imagine what the other techs in the chain are). I tried to fix it by attaching all pairs of such techs using UpDownLinearConstraints. Unfortunately that doesn't have the expected result, instead causing such chains to cross over each other:
![Unity_MPgijeYuxy](https://user-images.githubusercontent.com/2258788/79273086-59825b00-7e9a-11ea-9483-f4a13877685e.png)

Just for kicks, I also tried the same layer neighbor on the same set of techs, and ended up with the best result so far:
![Unity_um8VUjGtxn](https://user-images.githubusercontent.com/2258788/79273598-28565a80-7e9b-11ea-8a59-f30657fdee1a.png)

While that's fine though, the objective really is to generate something close to the first layout, but with linear chains constrained to stay connected. Is there something I'm missing?

**Comment by levnach** [comment]
@rwvens , thank your for the kind words! 
I would not go with constraints. In general, the layouts with constraints do not look very natural because, well, of the constraints, the optimization algorithms do not do the best job. Instead I'd try to increase SugiyamaSettings.BrandesThreshold to some very large number. 
By default, when the number of the nodes in the graph is greater than 600 MSAGL switches to the algorithm described here : https://www.semanticscholar.org/paper/Fast-and-Simple-Horizontal-Coordinate-Assignment-Brandes-K%C3%B6pf/69cb129a8963b21775d6382d15b0b447b01eb1f8.
It works fast, but creates these long edges that you complained about. If you set SugiyamaSettings.BrandesThreshold to a very large number, then the more accurate algorithm kicks in. It would take more time but the results should be better.

**Comment by rwvens** [comment]
Hey @levnach thanks for coming to the rescue. Unfortunately, the Brandes Threshold is not coming into play here, I set it to 9999 and it's still generating the same layout. Only reason it doesn't look exactly the same is because Destroyer II (0b) wasn't correctly depending on Destroyer I (d6), but the end of that chain, Destroyer IV (d0) still gets moved below its dependent chain (Dreadnought, depending on both Destroyer IV and Ironsides III)
![Unity_gUkoheBLbN](https://user-images.githubusercontent.com/2258788/79372474-cacf1600-7f4d-11ea-88df-a4fd7c39d3ca.png)

**Comment by levnach** [comment]
How large your graph is? Maybe it is the default layout working anyway. Another trick to use is the following one: if you want to keep an edge short assign a larger weight to it, Egde.Weight *= 10, or something like that. It might improve the situation.
Also please notice, that if d0 is moved to the left, 8f->d0 becomes shorter, then the edge  b4->59 becomes longer!

**Comment by rwvens** [comment]
Thanks, man, that did exactly what I was hoping for!
![Unity_2E1mgy6mOW](https://user-images.githubusercontent.com/2258788/79381183-7d58a600-7f59-11ea-9b0c-91bb67879456.png)
